// ----------USER STATUS-------------- //
export const USER_LOGGED = 'USER_LOGGED';
export const USER_LOGOUT = 'USER_LOGOUT';

// ---------- GET CHARACTERS LIST-------------- //
export const GET_CHARACTERS_LIST_STARTED = 'GET_CHARACTERS_LIST_STARTED';
export const GET_CHARACTERS_LIST_SUCCESS = 'GET_CHARACTERS_LIST_SUCCESS';
export const GET_CHARACTERS_LIST_FAILED = 'GET_CHARACTERS_LIST_FAILED';

// ---------- GET LOCATIONS LIST-------------- //
export const GET_LOCATIONS_LIST_STARTED = 'GET_LOCATIONS_LIST_STARTED';
export const GET_LOCATIONS_LIST_SUCCESS = 'GET_LOCATIONS_LIST_SUCCESS';
export const GET_LOCATIONS_LIST_FAILED = 'GET_LOCATIONS_LIST_FAILED';

// ---------- GET EPISODES LIST-------------- //
export const GET_EPISODES_LIST_STARTED = 'GET_EPISODES_LIST_STARTED';
export const GET_EPISODES_LIST_SUCCESS = 'GET_EPISODES_LIST_SUCCESS';
export const GET_EPISODES_LIST_FAILED = 'GET_EPISODES_LIST_FAILED';
